ENV: local
SERVICE:
  NAME: task-service
  HOST: "0.0.0.0"
  PORT: "8080"

LOG_LEVEL: INFO
LOG_FILE: stdout

DATABASE:
  DRIVER: mysql
  HOST: 127.0.0.1
  PORT: 3306
  USERNAME: root
  PASSWORD: pass
  DBNAME: task-service
  CHARSET: utf8mb4
  POOL_SIZE: 100
  TIMEOUT: 1s
  READ_TIMEOUT: 1s
  WRITE_TIMEOUT: 1s

CACHE:
  HOST: 127.0.0.1
  PORT: 6379

MIGRATION_FILE_PATH: ./migrations
