version: '3.8'

services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task-service
      MYSQL_ROOT_PASSWORD: pass

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  service-build:
    build:
      context: .
      dockerfile: build/dockerfile
    image: task_service:latest
 

  task_service:
    image: task_service:latest
    ports:  
      - 8080:8080
    environment:
      - DATABASE.HOST=mysql
      - CACHE.HOST=redis
    depends_on:
      - mysql
      - redis
    restart: always
 