
CREATE TABLE IF NOT EXISTS Task (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(200) NOT NULL,
    `status` TINYINT(1) NOT NULL DEFAULT 1,
    `content` VARCHAR(500) NOT NULL,
    `tag` VARCHAR(50) DEFAULT NULL,
    `version` int DEFAULT 1 ,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
